### ISSUE TITLE
Delayed plugins are disabled if Lazy Plugin Loader is disabled

### ISSUE THREAD

**Issue by Gr33ndev** [alangrainger/obsidian-lazy-plugins#1]
### Expected Behavior
The plugins that were set to be delayed should be active as normal when the Lazy Plugin Loader Plugin is disabled.

### Actual Behavior
The plugins set to be delayed are disabled when the Lazy Plugin Loader Plugin is disabled.

### Steps to Reproduce
1. Delay the start of a plugin.
2. Disable the Lazy Plugin Loader Plugin.
3. Restart Obsidian.
4. Check if the delayed plugin is activated or deactivated.

### Current workaround
1. Go to Lazy Plugin Loader options
2. Set all plugins to "Instant"
3. Restart Obsidian
4. Disable Lazy Plugin Loader
5. Restart Obsidian

### Additional Information
- Obsidian Version: v1.6.7
- Plugin Version: 1.0.2
- Operating System: macOS 14.5

**Comment by alangrainger** [comment]
Good suggestion and excellent Issue creation! - deployed in 1.0.3

**Comment by Gr33ndev** [comment]
Many thanks for the quick fix :)
