### ISSUE TITLE
[Feature Request] Load plugins sequentially

### ISSUE THREAD

**Issue by nuudlman** [alangrainger/obsidian-lazy-plugins#14]
I have a lot of heavy plugins set to load on the long delay (excalidraw, dataview, etc), so when they load in there is a huge stutter, especially on mobile. Would it be possible to add an option to load plugins in sequentially so that there isn't such a stutter?

If this is already the case, is there a different way to reduce that stutter?

**Comment by alangrainger** [comment]
I have good news for you - plugins [already _do_ load sequentially](https://github.com/alangrainger/obsidian-lazy-plugins/blob/15613d17fbc8a912a8dcef4fdc68fd9f248e8f33/src/main.ts#L67-L69), and you can increase the length of time between them.

Edit the `data.json` file in your `plugins/lazy-plugins` folder, and increase the delay for the `delayBetweenPlugins` setting. (Original setting is 40 milliseconds)
