### ISSUE TITLE
[feature request] Different settings for Mobile/Desktop

### ISSUE THREAD

**Issue by ZeroKun265** [alangrainger/obsidian-lazy-plugins#3]
Different settings for mobile and desktop would be a nice addition, similar to how the homepage plugin does it
For example the Tasks plugin needs to be instant on mobile, since I mark down my tasks there, but on PC it doesn't need to be
Also PC could load more plugins instantly since it's faster

Just a suggestion, love the performance improvement!

**Comment by alangrainger** [comment]
Good suggestion :+1:  This is added in 1.0.6
