### ISSUE TITLE
[BUG] Obsidian won't load the vault after enabling the plugin

### ISSUE THREAD

**Issue by dartungar** [alangrainger/obsidian-lazy-plugins#7]
Hey! Thanks for the great plugin... that's what I'd say if it didn't prevent Obsidian from loading 🥲
That's the screen I get after installing the plugin and relaunching Obsidian:
![image](https://github.com/user-attachments/assets/7d561ca6-d28c-4776-a4a6-d34bcef876c7)

And that's what I see in dev console:
![image](https://github.com/user-attachments/assets/332b5d30-6308-4318-aa5e-68fe95f0f59d)

Notably, "Reload app" and even "Reload app in restricted mode" did not help.
I also tried setting all plugins to "Disabled" in Lazy's settings - to no avail.

What did help is manually editing `.obsidian/community-plugins.json` and deleting your plugin's name from there. After that, everything loaded normally.

edit: setting all plugins to "Instant" also seems to help.

**Comment by alangrainger** [comment]
Very interesting. It must be something unique to your vault, so can you try it in a new test vault, and add your plugins in one-by-one to find the one which is causing this conflict?

**Comment by dartungar** [comment]
@alangrainger I've done a bit of fumbling around - this seems to be somehow related to catalyst version (1.7.1) of Obsidian.
I think we can bench this for now and see if anybody has the same problem after 1.7 gets a proper release.
