### ISSUE TITLE
Mobile/desktop config not working

### ISSUE THREAD

**Issue by peterlaxalt** [alangrainger/obsidian-lazy-plugins#9]
**Describe the bug**
Either I can't find the mobile/desktop config options or it's not working properly. 

I was excited to set the configuration on mobile to disable a lot of plugins I wouldn't even use on mobile (Obsidian iOS app, vault loaded via iCloud). Because I couldn't find the mobile only settings, I assumed you were clever and if I set the settings on my phone, they would be respected only for my phone. To my surprise I opened my desktop app and I had a ton of plugins disabled, realizing it was loading the last config I set assuming it was mobile only. 

**To Reproduce**
1. Turn on "separate desktop/mobile configuration"

**Expected behavior**
I'd assume either the settings I set on my phone are respected automatically or there is additional dropdown options for behavior (i.e. "short delay, desktop only").

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: N/A
 - Version: Latest

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max
 - OS: iOS
 - Browser: N/A 
 - Version: 18.0

**Comment by alangrainger** [comment]
Did you turn on separate desktop/mobile configuration on your phone?

**Comment by alangrainger** [comment]
I've added some extra text in 1.0.17 just now so you can tell which one you're editing:

![image](https://github.com/user-attachments/assets/7230d188-0643-4749-b73c-77e3b53c6b74)

**Comment by peterlaxalt** [comment]
Yep, seems the bug is that I had to turn it on/off on mobile in order for it to work. The logic does help, but I'd assume if I check on desktop, mobile is already in the mobile edit mode.
